IAMService/pom.xml
IAMService/src/main/java/rs/edu/raf/IAMService/configuration/SpringSecurityConfig.java

fixed spring sec. Resolved issue java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter

Fix spring sec. Resolved issue ClassNotFoundException DatatypeConverter

---

NotificationService/pom.xml
NotificationService/src/main/java/rs/edu/raf/NotificationService/services/EmailService.java
NotificationService/src/main/resources/application.properties
NotificationService/src/test/java/rs/edu/raf/NotificationService/EmailServiceTests.java

#20
U NotificationServisu dodao dependency: "spring-boot-starter-mail" za slanje mejlova i "com.icegreen" za testiranje mejlova (server vidi da li su mejlovi poslani i njihov context)
EmailService : Slanje mejlova (Simple, With Attachments, HTML), ako je potrebno moze se dodati i kompleksniji tipovi ili da se korisit emailService.sendMessage(message) i definise kompleksna poruka pre poziva metoda.
Notification Service application properties : dodao sam informacije za mejl server
Napravio sam mejl radi testiranja:
banka2raf@gmail.com, Gmail zahteva 2StepVerifcation pa nije lako ulogovati se (potrebna je sifra i telefon) ali uspesno se salju mejlovi
sifra za mejl: bankaraf123, APP Password (ovo je jedino bitno): rzpn vanx vxpr ewjo
Testiranje: test za uspesno slanje mejla i njegovog …

BE - Notification servis - slanje mejlova

---

IAMService/src/main/java/rs/edu/raf/IAMService/configuration/SpringSecurityConfig.java
IAMService/src/main/java/rs/edu/raf/IAMService/controllers/PermissionController.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/PermissionDto.java
IAMService/src/main/java/rs/edu/raf/IAMService/mapper/PermissionMapper.java
IAMService/src/main/java/rs/edu/raf/IAMService/repositories/PermissionRepository.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/PermissionService.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/PermissionServiceImpl.java
IAMService/src/test/java/rs/edu/raf/IAMService/permissions/PermissionControllerUnitTest.java
IAMService/src/test/java/rs/edu/raf/IAMService/permissions/PermissionServiceUnitTests.java

Implementirao sam kontroler, servis, repo i utility klase. Zbog testiranja sam ostavio da moja ruta ne prolazi kroz autentifikaciju u spring security konfiguraciji. Odradio unit testove za servis i kontroler.

Implementiran endpoint, dto i maper za permisije

---

IAMService/src/main/java/rs/edu/raf/IAMService/configuration/SpringSecurityConfig.java
IAMService/src/main/java/rs/edu/raf/IAMService/controllers/RoleController.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/RoleDto.java
IAMService/src/main/java/rs/edu/raf/IAMService/mapper/RoleMapper.java
IAMService/src/main/java/rs/edu/raf/IAMService/repositories/RoleRepository.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/RoleService.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/RoleServiceImpl.java

Implementirani svi zahtevi, ostalo je da odradim testove.

Kreiran repo, servis i kontroler za role, task #4

---

NotificationService/pom.xml
NotificationService/src/main/java/rs/edu/raf/NotificationService/configuration/RabbitMQConfig.java
NotificationService/src/main/java/rs/edu/raf/NotificationService/data/dto/EmailDto.java
NotificationService/src/main/java/rs/edu/raf/NotificationService/data/dto/PasswordActivationDto.java
NotificationService/src/main/java/rs/edu/raf/NotificationService/data/dto/PasswordChangeDto.java
NotificationService/src/main/java/rs/edu/raf/NotificationService/listener/PasswordListener.java
NotificationService/src/main/java/rs/edu/raf/NotificationService/mapper/EmailDtoMapper.java
NotificationService/src/test/java/rs/edu/raf/NotificationService/listenertest/PasswordListenerSpringTest.java
NotificationService/src/test/java/rs/edu/raf/NotificationService/listenertest/PasswordListenerUnitTest.java

Implementirani listener-i za redove password-change i password-activation, DTO-ovi za dolazece poruke i za email koji se generise iz tih objekata. Napisan unit testovi za ova dva listener-a. PasswordListenerSringTest je disabled jer sluzi samo za lakse manuelno testiranje listener-a.

PR za issues #18 i #12

---

IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/CorporateClientDto.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/EmployeeDto.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/PrivateClientDto.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/UserDto.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/enums/RoleType.java
IAMService/src/main/java/rs/edu/raf/IAMService/jwtUtils/JwtUtil.java
IAMService/src/main/java/rs/edu/raf/IAMService/mapper/UserMapper.java

#promenjen dto, tako da ima smisla za request, mapper, i ostalo da podrzi promenu za dto
primer kako request/response sad izgleda 
{
"id": 1,
"dateOfBirth": null,
"email": "email",
"username": "username",
"phone": "phone",
"address": "adress",
"role": "ADMIN",
"permissions": [Permission_1...]
}

Promena za dto, mapper

---

NotificationService/src/main/java/rs/edu/raf/NotificationService/configuration/RabbitMQConfig.java
NotificationService/src/main/java/rs/edu/raf/NotificationService/data/dto/ProfileActivationCodeDto.java
NotificationService/src/main/java/rs/edu/raf/NotificationService/listener/PasswordListener.java
NotificationService/src/main/java/rs/edu/raf/NotificationService/mapper/EmailDtoMapper.java
NotificationService/src/test/java/rs/edu/raf/NotificationService/listenertest/PasswordListenerSpringTest.java
NotificationService/src/test/java/rs/edu/raf/NotificationService/listenertest/PasswordListenerUnitTest.java

Dodao sam listener za user-profile-activation-code i napisao testove.

Issue #59 odradjen

---

IAMService/src/test/java/rs/edu/raf/IAMService/services/impl/UserServiceImplTest.java

Dodati unit testovi za metode iz issue-a 8.

Dodati testovi za Issue#8

---

IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
IAMService/src/main/java/rs/edu/raf/IAMService/repositories/UserRepository.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/PermissionService.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/UserService.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java

Postavljenje metode za 4 zahteva funkcionalnosti nad permisijama korisnika.

BE - IAMService - upravljanje permisijama nad korisnicima #9

---

IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/AgentDto.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/SupervisorDto.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/entites/Agent.java
IAMService/src/main/java/rs/edu/raf/IAMService/data/entites/Supervisor.java
IAMService/src/main/java/rs/edu/raf/IAMService/mapper/UserMapper.java
IAMService/src/test/java/rs/edu/raf/IAMService/mapper/UserMapperTest.java

U specifikaciji sam video da agenti imaju limit(mozda kasnije treba da se doda jos nesto). Za supervizore nisam nasao neki poseban atribut za dodavanje.

#101 - Kreiranje entiteta za supervizore i agente

---

IAMService/src/main/java/rs/edu/raf/IAMService/controllers/CompanyController.java
IAMService/src/main/java/rs/edu/raf/IAMService/repositories/CompanyRepository.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/CompanyService.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/CompanyServiceImpl.java
IAMService/src/test/java/rs/edu/raf/IAMService/CompanyServiceCrudTests.java

Implementiran endpoint za dovlacenje kompanije po maticnom broju i unit test za servis.

Find company by identification number implemented.

---

StockService/src/main/java/rs/edu/raf/StockService/controllers/CurrencyController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/ExchangeController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/ForexController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/OptionController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/StockController.java

samo dodat ```@CrossOrigin```, za slucaj da cors puca na frontu zbog toga u stock servicu

dodat @CrossOrigin za cors eventualno

---

NotificationService/src/main/resources/application.properties
NotificationService/src/test/java/rs/edu/raf/NotificationService/listenertest/RabbitMQListenersSpringTest.java
docker-compose.yml

uradjen docker compose i app.properties tako da se notifikacioni servis uspesno konektuje sa rabbitmq i da ne izbada svaki cas kako ne moze da se konektuje

issue kod notifikacionog servica i dockera

---

IAMService/src/main/java/rs/edu/raf/IAMService/controllers/CompanyController.java
IAMService/src/main/java/rs/edu/raf/IAMService/controllers/PermissionController.java
IAMService/src/main/java/rs/edu/raf/IAMService/controllers/RoleController.java
IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/CurrencyController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/ExchangeController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/ForexController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/OptionController.java
StockService/src/main/java/rs/edu/raf/StockService/controllers/StockController.java
StockService/src/main/java/rs/edu/raf/StockService/data/entities/Currency.java
StockService/src/main/java/rs/edu/raf/StockService/repositories/CurrencyRepository.java
StockService/src/main/java/rs/edu/raf/StockService/services/impl/CurrencyServiceImpl.java

reci ljudima da isprave svoj deo, ili neko da poglead

http uredjen i greske stavljene iznad metoda

---

NotificationService/src/test/java/rs/edu/raf/NotificationService/listenertest/RabbitMQListenersUnitTest.java

Zbog promena u RabbitMQListener-u morao sam da ispravim neke testove.

Ispravljeni testovi.

---

IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/CompanyServiceImpl.java
IAMService/src/test/java/rs/edu/raf/IAMService/controllers/CompanyControllerTest.java

Fixes #154 Company Controller Test fixes
CompanyController i CompanyControllerTest koriste iste requestove
npr greska je bila "api/companies/update-company" u testu ali "api/companies/update/ u controleru

BE - TESTOVI CompanyController

---

BankService/src/main/java/rs/edu/raf/BankService/BankServiceApplication.java
BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
BankService/src/main/java/rs/edu/raf/BankService/configuration/SpringSecurityConfig.java
BankService/src/main/java/rs/edu/raf/BankService/controller/CreditController.java
BankService/src/main/java/rs/edu/raf/BankService/data/dto/CreditDto.java
BankService/src/main/java/rs/edu/raf/BankService/data/dto/CreditRequestDto.java
BankService/src/main/java/rs/edu/raf/BankService/data/entities/Credit.java
BankService/src/main/java/rs/edu/raf/BankService/data/entities/CreditRequest.java
BankService/src/main/java/rs/edu/raf/BankService/data/enums/CreditRequestStatus.java
BankService/src/main/java/rs/edu/raf/BankService/data/enums/CreditType.java
BankService/src/main/java/rs/edu/raf/BankService/mapper/CreditMapper.java
BankService/src/main/java/rs/edu/raf/BankService/repository/credit/CreditRepository.java
BankService/src/main/java/rs/edu/raf/BankService/repository/credit/CreditRequestRepository.java
BankService/src/main/java/rs/edu/raf/BankService/service/CreditService.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapData.java

pogledaj malo, i javi sta da menjam/doradjujem @LukaPavlovicGit 
- Metoda za samo kreiranje kredita je veoma butcherovana jer tako specifikacija kaze, ali msm funkcionise na "predvidjen" nacin.
- Sve funkcionise i u postmanu i u swaggeru. 
- Kreirani Credit i CreditRequest entiteti za potrebe.
Pogledaj spring security, izmenio sam ga za potrebe kredita, postojeci kod funkcionise kako je funkcionisao. Stavio sam da security radi za kredite,  ostalo nisam dirao.
- Posto nista u accountu nije unique, on stalno dodaje identicne accountove samo sa razlicitim id-em, pa sam stavio da to radi samo ako je baza prazna.
- Dodao jedan credit i jedan credit request, po potrebi mogu dodati vise. 
- napraviti testove (gledacu da zavrsim do petka)
- da promenim sta treba, samo javi
- openApi doc

Krediti u bank servisu

---

BankService/src/main/java/rs/edu/raf/BankService/controller/CardController.java
BankService/src/main/java/rs/edu/raf/BankService/data/dto/CardDto.java
BankService/src/main/java/rs/edu/raf/BankService/data/entities/card/Card.java
BankService/src/main/java/rs/edu/raf/BankService/data/enums/CardType.java
BankService/src/main/java/rs/edu/raf/BankService/mapper/CardMapper.java
BankService/src/main/java/rs/edu/raf/BankService/repository/CardRepository.java
BankService/src/main/java/rs/edu/raf/BankService/service/CardService.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/CardServiceImpl.java
BankService/src/test/java/resources/cardFeatures.feature
BankService/src/test/java/rs/edu/raf/BankService/creditTests/CardControllerTests.java
BankService/src/test/java/rs/edu/raf/BankService/creditTests/CardServiceTests.java
BankService/src/test/java/rs/edu/raf/BankService/creditTests/integrationTests/CardIntegrationSteps.java
IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapData.java

Napravljeno za kartice contoler, service itd. Nije samo implementirano placanje i transakcije (nisam siguran da li ja to radim). Uradjeni unit i integracioni testovi. 
Dodati  novi korisnici i popunjeni stari da nema bas svuda null.

Kartice i Novi korisnici u bootstrapu

---

BankService/src/main/java/rs/edu/raf/BankService/controller/CreditController.java
BankService/src/main/java/rs/edu/raf/BankService/data/dto/CreditRequestDto.java
BankService/src/main/java/rs/edu/raf/BankService/data/entities/credit/Credit.java
BankService/src/main/java/rs/edu/raf/BankService/data/entities/credit/CreditRequest.java
BankService/src/main/java/rs/edu/raf/BankService/repository/credit/CreditRequestRepository.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java

Credit Request findAll sad vraca findAllPending, ako hocete da gledate i ostale javite.
za credit i req equals+hashCode

CreditRequestovi updateovani da se vracaju samo pending

---

BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTestSteps.java
BankService/src/test/java/rs/edu/raf/BankService/integration/credit/CreditStepsDefinition.java
BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java

promenjeni krediti tako da ti zapravo doda pare ne racun, i testovi da podrze promenjeno
i stavljeni requestovi da imaju provere za currency
ako je foreign acc dodace u holder, ako je dinarski dodace direktno

Fix za kredite 

---

BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateBootstrapUtil.java
BankService/src/main/java/rs/edu/raf/BankService/data/dto/ExchangeRequestDto.java
BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/ForeignCurrencyAccount.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeControllerTests.java
BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeServiceTests.java
BankService/src/test/resources/features/e2e/currencyExchangeController/currencyExchangeFeatuesE2E.feature

promenjena menjacnica i krediti da rade sa samo jednom valutom ako je devizni racun.

vise se ne koristi foreignAccHolder

---

IAMService/src/test/java/rs/edu/raf/IAMService/e2e/companycontroller/CompanyControllerSteps.java
IAMService/src/test/java/rs/edu/raf/IAMService/e2e/companycontroller/CompanyControllerTests.java
IAMService/src/test/java/rs/edu/raf/IAMService/e2e/companycontroller/CompanyControllerTestsConfig.java
IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/company/CompanyServiceTests.java
IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/company/CompanyServiceTestsConfig.java
IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/company/CompanyServiceTestsSteps.java
IAMService/src/test/resources/features/companyservice/Create Company.feature
IAMService/src/test/resources/features/companyservice/Delete Company By Identification Num.feature
IAMService/src/test/resources/features/companyservice/Get Companies.feature
IAMService/src/test/resources/features/companyservice/Update Company.feature
IAMService/src/test/resources/features/e2e/companycontroller/CompanyController.feature
StockService/src/test/java/rs/edu/raf/StockService/e2e/currencycontroller/CurrencyControllerTests.java
StockService/src/test/java/rs/edu/raf/StockService/e2e/currencycontroller/CurrencyControllerTestsConfig.java
StockService/src/test/java/rs/edu/raf/StockService/e2e/currencycontroller/CurrencyControllerTestsSteps.java
StockService/src/test/java/rs/edu/raf/StockService/integration/currencyservice/CurrencyServiceImplTests.java
StockService/src/test/java/rs/edu/raf/StockService/integration/currencyservice/CurrencyServiceImplTestsConfig.java
StockService/src/test/java/rs/edu/raf/StockService/integration/currencyservice/CurrencyServiceImplTestsSteps.java
StockService/src/test/resources/features/e2e/currencycontroller/CurrencyController.feature
StockService/src/test/resources/features/integration/currencyservice/CurrencyServiceImpl.feature

Integracioni testovi za kompanije implementirani. Currency i e2e testovi su zakomentarisani i nisu zavrseni do kraja posto dosta sporo ide i imam tehnickih poteskoca, nisam uspeo da nadjem adekvatno resenje oko racunara, nastavicu u toku dana sa e2e i currency testovima.

Integracioni testovi za kompanije i currency

---

BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapData.java

dodati da privatni korisnici imaju naloge lol i bugifx za credit requestove posto je menjan rad sa currencijima na nalogu

bootstrap data za andreja da bude smislenije, i credit req buffxi

---

IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java

promenjen delete user da vraca unathorized umesto -1 za front

andrej delete user

---

IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java

dodati springsecurity za metode za sueprvisora

andrej security za supervisora

---

IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java

setuje se dummy password, koji mora da se promeni pre logovanja, kako se ne bi izbrisao korisnik pre nego sto dobije uopste priliku da se uloguje. ovo je bukv quick fix, treba izmeniti naknadno sa nekim boljim resenjem ( npr creationDate da se cuva i po njemu da se ne brise u kron jobu)

bugfix za createuser

---

BankService/src/main/java/rs/edu/raf/BankService/data/enums/OrderActionType.java
BankService/src/main/java/rs/edu/raf/BankService/repository/SecuritiesOwnershipRepository.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
BankService/src/main/java/rs/edu/raf/BankService/service/impl/SecuritiesOwnershipServiceImpl.java
BankService/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java

uradjeni trading jobovi za sada, verovatno ce trebati da se izmeni u nekom trenutku kada se zavrsi otc i zapravo budemo mogli da testriamo kako treba, ali okvirno je to to 
sell_to_stock_market- ako se selluje berzi, radi se odmah-> dobija pare iz abyssa i listing ide u abyss,
sell-> ako se selluje drugom korisniku, samo ceka da se izvrsi neki buy, jer ce on promeniti vrednosti ( kad se zapravo desi kupovina/transakcija)

uradjeni buy/sell trading jobs

---

bank-service/src/main/java/rs/edu/raf/BankService/controller/OrderTransactionController.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/ForexDto.java
bank-service/src/main/java/rs/edu/raf/BankService/repository/OrderTransactionRepository.java
bank-service/src/main/java/rs/edu/raf/BankService/service/OrderTransactionService.java
bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderTransactionServiceImpl.java
bank-service/src/main/java/rs/edu/raf/BankService/service/impl/StockServiceImpl.java
bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
docker-compose.yml
stock-service/src/main/java/rs/edu/raf/StockService/controllers/ForexController.java

- rade orderi za forex
- orderTransaction entitet za cuvanje i prikazivanje order transakcija sa 4-5 find metoda

orderi->forex+transakcije

---

bank-service/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java

Reverts RAF-SI-2023/Banka-2-Backend#300

Revert "Obrisan config zxa hibernetes"

---

iam-service/src/main/java/rs/edu/raf/IAMService/data/entites/Role.java

Reverts RAF-SI-2023/Banka-2-Backend#298

Revert "Lazy to eager stratefgy"

---

bank-service/src/main/java/rs/edu/raf/BankService/MarginsAccountMaintainScheduler.java
bank-service/src/main/java/rs/edu/raf/BankService/configuration/RabbitMQConfig.java
bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsAccountController.java
bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsTransactionController.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginCallViolationDto.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountRequestDto.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountResponseDto.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionRequestDto.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionResponseDto.java
bank-service/src/main/java/rs/edu/raf/BankService/data/entities/MarginsAccount.java
bank-service/src/main/java/rs/edu/raf/BankService/data/entities/MarginsTransaction.java
bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsAccountMapper.java
bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsTransactionMapper.java
bank-service/src/main/java/rs/edu/raf/BankService/repository/MarginsTransactionRepository.java
bank-service/src/main/java/rs/edu/raf/BankService/repository/specification/MarginsTransactionSpecification.java
bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsAccountService.java
bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsTransactionService.java
bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsAccountServiceImpl.java
bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java
notification-service/src/main/java/rs/edu/raf/NotificationService/data/dto/MarginCallViolationDto.java
notification-service/src/main/java/rs/edu/raf/NotificationService/listener/RabbitMQListeners.java
stock-service/src/main/java/rs/edu/raf/StockService/configuration/SpringSecurityConfig.java
stock-service/src/main/java/rs/edu/raf/StockService/controllers/BankServiceCommunicationController.java

NIJE SKROZ TESTIRANO!
Pull request kreiran radi potencijalnog integrisanja sa front-om
Ostalo je da se odradi: Likvidacija pozicija za hartije koje korisnik poseduje radi izmirenje Margin Call-a (74 strana specifikacije)
Previse konfuzan opis, trebace mi konsultacija sa nekim

Skoro zavrsen marzni racun

---

bank-service/src/main/java/rs/edu/raf/BankService/service/impl/BankTransferTransactionDetailsServiceImpl.java

Reverts RAF-SI-2023/Banka-2-Backend#347

Revert "Editovan transferTransactionDetails"

---

bank-service/src/main/java/rs/edu/raf/BankService/MarginsAccountMaintainScheduler.java
bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsAccountController.java
bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsTransactionController.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountRequestDto.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountResponseDto.java
bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionResponseDto.java
bank-service/src/main/java/rs/edu/raf/BankService/data/entities/MarginsTransaction.java
bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsAccountMapper.java
bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsTransactionMapper.java
bank-service/src/main/java/rs/edu/raf/BankService/repository/MarginsAccountRepository.java
bank-service/src/main/java/rs/edu/raf/BankService/repository/specification/MarginsTransactionSpecification.java
bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsAccountService.java
bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsTransactionService.java
bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsAccountServiceImpl.java
bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java

Sredjene neke stvari oko modela i dodate metode za fleksibilnije dovlacenje racuna i transakcija

Sredjivanje marznih racuna i transakcija

---

bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java

Dodato je samo da stock-ovi od banke imaju neku kolicinu publicAvaliableQuantity-ja

Dodata mal promena u bootstrap u bank-service-u
